# Generated by Django 4.0.6 on 2022-07-26 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_color_list', models.CharField(choices=[('#00FF00', '#00FF00'), ('#ff0000', '#ff0000'), ('#0000FF', '#0000FF')], default='#00FF00', max_length=7)),
                ('card_color', models.CharField(max_length=275, null=True)),
                ('card_inner_message', models.TextField(max_length=300)),
                ('card_outer_message', models.TextField(max_length=300)),
                ('card_image', models.CharField(max_length=275)),
                ('card_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greeting_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
