# Generated by Django 4.0.6 on 2022-08-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards_api', '0004_alter_greetingcard_card_color_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetingcard',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images', max_length=400),
        ),
    ]
