# Generated by Django 4.0.6 on 2022-08-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards_api', '0007_rename_image_greetingcard_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingcard',
            name='card_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='card_images'),
        ),
        migrations.AlterField(
            model_name='greetingcard',
            name='card_image',
            field=models.CharField(blank=True, max_length=275, null=True),
        ),
    ]
