# Generated by Django 4.0.6 on 2022-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards_api', '0008_greetingcard_card_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetingcard',
            name='card_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='greetingcard',
            name='card_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
