# Generated by Django 4.0.6 on 2022-08-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards_api', '0017_remove_greetingcard_card_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingcard',
            name='card_image_file',
            field=models.ImageField(blank=True, max_length=600, null=True, upload_to='card_images'),
        ),
    ]
